services:
  - type: web                # Service‑Kategorie
    name: moviepy-render     # frei wählbar
    runtime: python          # <‑‑ Blueprint erwartet "runtime", nicht "env"
    plan: free               # free / starter / standard …
    region: frankfurt        # optional, aber sinnvoll

    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"

    envVars:
      - key: RENDER_PYTHON_PACKAGE_INSTALL
        value: pip
